---
abstract: 'Log::Any::App which uses Log::Dispatch::FileWriteRotate for file output'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Slurp: 0
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alt-Log-Any-App-FWR
requires:
  Alt::Base: 0.01
  File::HomeDir: 0
  File::Path: 2.07
  File::Write::Rotate: 0.10
  JSON: 0
  Log::Any: 0.14
  Log::Any::Adapter: 0.07
  Log::Any::Adapter::Log4perl: 0.06
  Log::Dispatch::Dir: 0.10
  Log::Dispatch::FileWriteRotate: 0.01
  Log::Dispatch::Syslog: 2.29
  Log::Log4perl: 1.36
  perl: 5.008000
resources:
  homepage: http://metacpan.org/release/Alt-Log-Any-App-FWR
  repository: http://github.com/sharyanto/perl-Alt-Log-Any-App-FWR
version: 0.06
